# 错误处理
在 Axum 的项目中自定义错误响应格式，可以通过实现 `IntoResponse` trait 来完成。这允许我们定义错误以及发生了该错误应返回对应的 HTTP 响应。

## 自定义错误类型
在 src 下新建 errors\.rs 用于实现错误处理。同时在 teacher-service\.rs 引入 mod：
```rust
#[path = "../errors.rs"]
mod errors;
```
目前程序中的错误可以分为页面找不到以及内部服务错误。其中，内部服务错误在本程序中仅用来反映数据库错误。对于数据库错误，我们需要实现 `From` trait 以转换。
文件路径：hello_axum/src/errors\.rs
```rust
use axum::{
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use serde_json::json;

#[derive(Debug)]
pub enum MyError {
    NotFound(String),
    InternalServerError(String),
}

impl IntoResponse for MyError {
    fn into_response(self) -> axum::response::Response {
        let (status, error_message) = match self {
            MyError::NotFound(msg) => (StatusCode::NOT_FOUND, msg),
            MyError::InternalServerError(msg) => (StatusCode::INTERNAL_SERVER_ERROR, msg),
        };

        // 创建一个JSON响应
        let response = Json(json!({
            "status": status.as_u16(),
            "error": error_message,
        }));

        // 将状态码和JSON响应组合成一个HTTP响应
        (status, response).into_response()
    }
}

impl From<sqlx::Error> for MyError {
    fn from(value: sqlx::Error) -> Self {
        Self::InternalServerError(value.to_string())
    }
}
```

## 在处理程序中使用
### `Result<T, E>` 类型中的 `map`
`map` 方法接受一个闭包作为参数，这个闭包对 `Result` 中的成功值进行操作。如果 `Result` 是 `Ok`，则将闭包应用于 `Ok` 中的值，并返回一个新的 `Result`，其中包含闭包的返回值。如果 `Result` 是 `Err`，则直接返回原始的 `Err`，不执行任何操作。

### `Result<T, E>` 作为 handler 的返回类型
对于 `Result<T, E>` 类型，Axum 提供了特殊的处理逻辑：
- 成功情况 `Ok(T)`：Axum 将 `T` 转换为 HTTP 响应。`T` 必须实现`IntoResponse` trait。
- 错误情况 `Err(E)`：Axum 将 `E` 转换为 HTTP 响应。`E`也必须实现`IntoResponse` trait。通常，`E` 会被转换为一个表示错误的 HTTP 响应，例如 400 Bad Request、404 Not Found 或 500 Internal Server Error 等。

### 可能的错误
#### 添加新课程
仅有可能发生数据库查询的错误，因此，把 `post_new_course_db` 中的 `unwrap()` 改为 `?`，并在之后返回 `Ok(course)`，修改返回类型为 `Result<Course, MyError>`：
```rust
pub async fn post_new_course_db(pool: &PgPool, new_course: Course) -> Result<Course, MyError> {
    let course: Course = // --snip--
    .await?;
    Ok(course)
}
```
修改对应的 handler：
```rust
pub async fn new_course(
    Extension(state): Extension<Arc<AppState>>,
    Json(new_course): Json<Course>,
) -> Result<Json<Value>, MyError> {
    post_new_course_db(&state.db, new_course).await
        .map(|course| Json(json!({"message": "Course Added", "new course": course})))
}
```

#### 其他错误
下面以同样的思路对其他函数进行修改。
##### 获取某个老师的所有课程
```rust
pub async fn get_courses_of_teacher_db(pool: &PgPool, teacher_id: i32) -> Result<Vec<Course>, MyError> {
    let select_courses: Vec<Course> = // --snip--
    .await?;
    match select_courses.len() {
        0 => Err(MyError::NotFound("No Courses found for teacher".into())),
        _ => Ok(select_courses),
    }
}
pub async fn courses_of_teacher(
    Path(teacher_id): Path<i32>,
    Extension(state): Extension<Arc<AppState>>
) -> Result<Json<Value>, MyError> {
    get_courses_of_teacher_db(&state.db, teacher_id).await
        .map(|courses| Json(json!(courses)))
}
```
##### 获取某个课程的信息
```rust
pub async fn get_course_detail_db(pool: &PgPool, teacher_id: i32, course_id: i32) -> Result<Course, MyError> {
    match sqlx::query_as::<Postgres, Course>(
        // --snip--
    )   // --snip--
    .await {
        Ok(course) => Ok(course),
        Err(_) => Err(MyError::NotFound("NotFoundCourse".into())),
    }
}
pub async fn course_detail(
    Path((teacher_id, course_id)): Path<(i32, i32)>,
    Extension(state): Extension<Arc<AppState>>,
) -> Result<Json<Value>, MyError> {
    get_course_detail_db(&state.db, teacher_id, course_id).await
        .map(|course| Json(json!(course)))
}
```