# <center>错误处理</center>

## 不可恢复的错误与panic!
panic!是不可恢复的错误，panic!宏打印错误信息并终止程序。
```rust
panic!("cargo and burn");
```
当程序出现错误也会造成panic!：
```rust
let v = vec![1, 2, 3];
v[9];   // 索引越界
```

## 可恢复的错误与Result
### Result枚举
```rust
enum Result<T, E> {
    Ok(T),          //操作成功
    Err(E),         //操作失败
}
```

### 处理Result的方式
#### match
```rust
let f = match File::open("my.txt") {
    Ok(file) => file,
    Err(error) => match error.kind() {
        Errorkind::NotFound => match File::create("my.txt") {
            Ok(file) => file,
            Err(error) => panic!("Error to Create:{:?}", error),
        }
        other_error => panic!("Error to Open:{:?}", other_error),
    }
};
```

#### unwrap_or_else
正确直接返回，错误进入后续处理。相比于match，对不出现错误的情况做了简化。
```rust
let f = File::open("my.txt").unwrap_or_else(|error| {
    if let ErrorKind::NotFound = error.kind() {
        File::create("my.txt").unwrap_or_else(|error| {
            panic!("Error to Create:{:?}", error);
        })
    } else {
        panic!("Error to Open:{:?}", error);
    }
});
```

#### unwrap和expect
- unwrap无后续处理，错误信息不可以自定义。
- expect也无法后续处理，但错误信息可以自定义。
```rust
let f = File::open("my.txt").unwrap();
let f = File::open("my.txt").expect("Error to Open");
```

#### 传递错误
如果在函数内部可能出现错误，但是想要外部调用来处理错误，就可以将返回类型设为Result，使用match决定返回值。
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = match File::open("my.txt") {
        Ok(file) => file,
        Err(error) => return Err(error),
    };
    let mut username = String::new();
    match f.read_to_string(&mut username) {
        Ok(username) => Ok(username),
        Err(error) => Err(error),
    }
}
```
这种方式代码重复部分多，使用`?`可以简化上述流程。
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();
    let mut f = File::open("my.txt")?;
    f.read_to_string(&mut username)?;
    Ok(username)
}
```
`?`符的实际作用是将`Result`类非异常的值直接取出，如果有异常就将异常`Result`返回出去。所以，`?`符仅用于返回值类型为`Result<T, E>`的函数，其中`E`类型必须和`?`所处理的`Result`的`E`类型一致。
使用`?`符的语句也支持链式调用：
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();
    File::open("my.txt")?.read_to_string(&mut username)?;
    Ok(username)
}
```

## 何时使用panic!
- 在定义一个可能失败的函数时，优先考虑返回Result
- 你认为Result一定是Ok时，使用unwrap
- 可以使用panic!--unwrap、expect
  1. 演示某些概念
  2. 原型代码：做panic标记，用于后续维护
  3. 测试
  4. 失败不可预期，无法修复
  5. 他人需要调用代码，传入参数无意义